lib/client.js
test/client.tests.js

Supports closing the `db` and cleaning up `client`'s event listeners.

Add `client.close()`

---

lib/client.js
lib/db.js
test/client.tests.js
test/db.tests.js

Also fixed some badly escaped regexps in tests.

Add `resetAll()` method to clear all keys of all buckets

---

lib/db.js

setImmediate runs after almost a whole event loop cycle (except close callbacks)
which means that what we put in setImmediate is affected by blocked "event loop
latency"; i.e. if anything between the point setImmediate is executed and the "check"
section of event loop blocks the event loop (for example one of the pending callbacks
in poll section), then latency of limiter will increase; even for the case of non-ratelimiting
(unlimited: true). This PR replaces setImmediate by process.nextTick, nextTick is executed
after current function but before the event loop is allowed to continue, providing a very low
latency for the case of not-rate-limit.

Replace setImmediate with process.nextTick

---

lib/client.js
lib/db.js
test/client.tests.js
test/db.tests.js

There is a need to check the current value for a single given key without modifying it. This implements it and keeps parity with limitd/limitdb

CAUTH-33 Add support for GET

---

lib/client.js
lib/db.js

Increase the frequency in which slots are calculated to 5 minutes. In the case of a failover, the first `MOVED` will force a slots refresh faster thus reducing the impact window significantly.
Increase the slots command timeout to 3s (failure can be tolerated most of the time).
Separate the node errors from the actual errors. Therefore full cluster errors will go through `error` while a single node timing out would go into `node errors`

Separate node error from error

---

.gitignore
README.md
lib/client.js
lib/db.js
lib/utils.js
lib/validation.js
package.json
test/db.tests.js
test/validation.tests.js

Per slack thread, we need a way for tenants to be able to customize Suspicious IP Throttling rates.  Since the existing `DynamicClientConfigurationProxy` + MongoDB store will not scale, we're passing in bucket configuration at runtime.
One big downside to this approach: if the caller(s) do not all retrieve tenant settings and pass them in appropriately, then we will get mixed results.  For instance, if a user gets blocked from auth0-server where a tenant override is passed in to a `take` operation, it's possible that the same user will not show up in API2 as blocked if API2 does not retrieve and pass in the same tenant settings to its `get` operation.  Can try to mitigate with wrappers/enhancements, but it's less-than-ideal.
- https://auth0.slack.com/archives/C01J73CL4A3/p1627656818000500? …

[CAUTH-954] Pass in bucket configuration at runtime

---

lib/db.js
test/db.tests.js

Check for non integer count, with a fast-fail for invalid counts (such as '1', 0.5, etc). 
[IAMRISK-1454]
`npm test`
[IAMRISK-1454]: https://auth0team.atlassian.net/browse/IAMRISK-1454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[IAMRISK-1454] check for non integer count

---

.gitignore
lib/put.lua
test/db.tests.js

When Redis does not hold a certain entry for a given key, we consider that this entry's bucket is full. Currently, if we call `put(count=n)` for this entry, the end result is a bucket with `n` tokens, but the we should actually just leave the bucket as is (full).
In this PR, I'm fixing this faulty behavior, by ensuring that calling `put()` over a full bucket results in a full bucket. It's quite a big change of behavior for the `put()` operation, might even be semver breaking, but arguably the older behavior is quite unexpected and I would be surprised that consumers rely on it. Would appreciate thoughts from the maintainers about this 🙇 
https://auth0team.atlassian.net/browse/IAMRISK-1455

IAMRISK-1455 fix(put): keep full bucket when already full

---

lib/db.js
package.json

Adding a `reconnectOnError` handler for ioredis client that will reconnect if an error is emitted from the client that includes `READONLY` in the message.
This is important for environments where auto failover is not enabled to minimize incidents in limitr use cases when a failover does occur with an elasticache cluster.
This mimics the behavior used in `belgrano`.
https://auth0team.atlassian.net/browse/PSERV-1561
https://github.com/auth0/belgrano/blob/62589d1e1d31ed5e91ea92a68c8a9b4da5fffc23/lib/cache/redis.js#L58-L63
https://github.com/luin/ioredis#reconnect-on-error

PSERV-1561 - Reconnect when readonly error is received from redis in Limitr client

---

README.md
lib/client.js
lib/db.js
lib/put.lua
lib/take.lua
lib/utils.js
package.json
test/db.tests.js

1. Cache non fixed sized buckets when empty up until the next drip.
2. Build reset from redis time instead of local time for correctness in both headers and cache ttl.
3. Minor fixes along with removing duplicate calculations
Naive benchmark code:
```js
it.only('bench', (done) => {
const startDisabled = Date.now();
async.eachSeries(_.range(10000), (_, done) => {
db.take({type: 'cached', key: 'disabled'}, done);
}, (err) => {
assert.ifError(err);
console.log('Cache Disabled', Date.now() - startDisabled);
const startEnabled = Date.now();
async.eachSeries(_.range(10000), (_, done) => {
db.take({type: 'cached', key: 'bench'}, done);
}, (err) => {
assert.ifError(err);
console.log('Cache Enabled', Date.now() - startEnabled);
done();
});
});
});
```
```
Cache Disabled 9531
Cache Enabled 29
``` …

Cache non-conformant answers and fix reset times

---

README.md
docker-compose.yml
lib/client.js
lib/db.js
lib/db_ping.js
lib/utils.js
package.json
test/db.tests.js

Added an app-level ping to determine if the connection with Redis is alive or not. This only works in single mode, as we're already covered for Cluster mode.
It will emit the following events:
- **ping - success**: Every time a ping is successfully answered by Redis.
- **ping - fail**: Every time a ping fails to be answered by Redis.
- **ping - reconnect attemped**: Every time the library attempts to reconnect with Redis.
This new feature is **DISABLED** by default. In order to enable it, the users will need to send a new **ping** attribute on the LimitDB constructor with the following format:
```javascript
ping = {
interval: 3000, //the ping interval expressed in ms. Defaults to 3000.
maxFailedAttempts: 5, //the max allowed failed attempts before trying to reconnect. Defaults to 5. …
```

feat:Allow to ping redis at app level and reconnect if it fails

---

README.md
lib/db.js
lib/utils.js
test/db.tests.js

This PR makes use of a  local count. Instead of going to Redis every time, with this new configuration will go to Redis every N time, helping to relieve some pressure over Redis when needed.

feat: relax take count's

---

lib/db.js
test/db.tests.js

This PR fixes an issue where `skip_n_calls` would inaccurately limit received requests.
<details><summary>Local Test Results</summary>
<p>
Tests generated locally using testing tools added here: https://github.com/auth0/platform-core-services-tools/pull/24/files
The graphs below show the number of conformant requests under the following conditions:
```
- 10 nodes making requests at 330 RPS (3300 total)
- global rate limit configured to 1000 RPS
```
Notice that it is limiting to **1.4k RPS** instead of **1k RPS**
The graph below shows the number of conformant requests under the following conditions:
```
- 10 nodes making requests at 330 RPS (3300 total)
- global rate limit configured to 1000 RPS
```
Notice that it is now correctly limiting to **1k RPS**
| Nodes | Limit Per Second | …

fix: [PSERV-2110] skip_n_calls take amount accounts for current call

---

package.json

Bumps version from `7.8.0` to `7.8.1`
New version includes
- fix for [skip_n_calls](https://github.com/auth0/limitd-redis/pull/50)
Note: Bumping the [patch](https://semver.org/) number here as it is a backwards compatible change.
<details><summary>Semantic Versioning</summary>
<p>
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backward compatible manner
> PATCH version when you make backward compatible bug fixes
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
https://semver.org/
</p>
</details> 
https://github.com/auth0/limitd-redis/pull/50
https://auth0team.atlassian.net/browse/PSERV-2110
N/A

chore: bump version to 7.8.1

---

README.md
lib/db.js
lib/take_elevated.lua
lib/utils.js
lib/validation.js
test/db.tests.js

This PR implements the core mechanism for a new rate limits capability called Elevated Rate Limits (ERL).
ERL is a feature that will allow defining a different set of limits that temporarily kick in when the bucket is empty. The feature aims to provide a way to temporarily allow a higher rate of requests when the bucket is empty, to reduce friction.
In its final form, the feature will allow setting a quota for how long and how many times ERL can be activated for a given bucket - however, this quota counting ability is out of the scope of this PR.
Please see changes to README for details on what needs to be provided to enable and use ERL.
Yes. You don't have to make any changes to your existing usages.
If a bucket has ERL configured, and `limitd.takeElevated` is called:
-- Whenever the …

feat: Elevated Rate Limits core mechanism  (#1)

---

README.md
lib/db.js
lib/take_elevated.lua
lib/utils.js
lib/validation.js
package.json
test/db.tests.js
test/utils.tests.js
test/validation.tests.js

This PR includes the Quota Counting mechanism for ERL.
ERL is a feature that will allow defining a different set of limits that temporarily kick in when the bucket is empty. The feature aims to provide a way to temporarily allow a higher rate of requests when the bucket is empty, to reduce friction.
> This PR completes the ERL feature that allows setting a quota for how long and how many times ERL can be activated for a given bucket.
Please see changes to README for details on what needs to be provided to enable and use ERL with quota counting.
Yes. You don't have to make any changes to your existing code using limitd-redis.
All the work has been done within the new takeElevated method.

feat:ERL quota counting

---

package.json

Updating `ioredis` to latest version 5.3.2, and updating package version to `8.0.0`. See migration guide here https://github.com/redis/ioredis/wiki/Upgrading-from-v4-to-v5.
No changes needed with this implementation of `ioredis` as we are already configuring `slotsRefreshInterval` by default.

Update ioredis v5

---

lib/db.js
test/db.tests.js

While executing the load tests, we realised that even when the ERL is being used, we’re displaying the normal bucket size in http headers. This is creating confusion as sometimes it causes the remaining to be higher than the limit.
This PR fixes this by making sure that if ERL was active on the request, the ERL bucket size is returned; and the normal bucket size otherwise.
https://auth0.slack.com/archives/C06DWRK540Y/p1714747757336829?thread_ts=1713272242.147539&cid=C06DWRK540Y

fix: return correct bucket size [PSERV-2452]

---

README.md
lib/db.js
lib/take_elevated.lua
lib/utils.js
lib/validation.js
package.json
test/client.tests.js
test/db.tests.js
test/utils.tests.js

This PR changes the way we track ERL quota to address an edge case where the ERL quota changes in the middle of the month (before quota reset at the beginning of the next month).
It also collects all ERL configuration in a single place, so that the bucket overrides functionality can also be applied to ERL configuration.
**Before**:
* The first time ERL was activated, it was setting in redis quotaKey = quotaGivenThroughParam . If quota=192, then quotaKey = 192 after that first activation.
* From that point on, every ERL activation it was basically decreasing the quota quotaKey = quotaKey-1
Until quotaKey=0 => then the tenant exhausted all the quota for the given month.
* With the current situation, if the quota configuration changes in the middle of the month, lets say from 192 to 384, …

Elevated rate limits incremental quota

---

lib/db.js
lib/take_elevated.lua
lib/utils.js
test/db.tests.js
test/utils.tests.js

We realised that the `takeElevated.lua` script wasn't working as expected -- it wasn't allowing the user to consume the last erl quota they have. The reason was that we were returning  1 as the `previously used quota` at the first ERL activation.
This PR fixes this issue, and adjusts the rest of the code accordingly.

fix: quota usage

---

.github/workflows/ci.yml

Adds some basic CI using github actions to run our test suite.
Adopt github actions for OSS tooling: https://oktawiki.atlassian.net/wiki/spaces/A0ENG/pages/2561368475/GitHub+Actions

ci: add basic CI with github actions

---

.github/workflows/ci.yml

Running CI on Node 20 as well, to ensure tests pass on Node 20, which is the current LTS.
N/A

Run CI on Node 20

---

README.md
lib/utils.js
test/utils.tests.js

Fixes an error we found when providing overrides.
**Problem detected:** If we only provided overrides for elevated_limits, with no override for base size and/or per_x, the final configuration would not include the size and per_x.
Example:
- Base bucket config
```
buckets = {
ip: {
size: 10,
per_second: 5,
overrides: {
'awesome-key': {
elevated_limits: {
size: 200,
per_second: 200,
}
}
}
}
}
```
When the override is processed, the configuration of the …

fix:allow to only override elevated limits but merging with original config

---

.github/workflows/ci.yml
Makefile
README.md
docker-compose-cluster.yml
lib/client.js
lib/db.js
package.json
test-resources/redis-cluster/node-1/conf/redis.conf
test-resources/redis-cluster/node-2/conf/redis.conf
test-resources/redis-cluster/node-3/conf/redis.conf
test-resources/redis-cluster/redis-cluster-create.sh
test/client.clustermode.tests.js
test/client.standalonemode.tests.js
test/client.tests.js
test/db.clustermode.tests.js
test/db.standalonemode.tests.js
test/db.tests.js

This PR adds the ability to include the username within the optional parameters of the LimitdRedis constructor to use it when connecting to a Redis Cluster.
For Standalone Redis instances, there's no need to include the username as an attribute as we support it through the connection URI.
- Added specific tests for the username
- Introduced clustered tests, which is running the same battery of tests against a clustered environment.

feat:support redis username

---

Makefile
README.md
lib/db.js
test/db.tests.js

Adds a new `delta_reset_ms` response attribute to TAKE and TAKEELEVATED, to indicate the number of ms until the bucket resets. Unlike the `reset` attribute which represents a unix timestamp, this attribute represents a delta from the current time expressed in ms in order to avoid clock skew issues.

feat: adding delta_reset_ms to TAKE and TAKEELEVATED responses

---

README.md
lib/client.js
lib/db.js
package.json
test/client.tests.js
test/db.clustermode.tests.js
test/db.standalonemode.tests.js
test/db.tests.js

_By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo._
We are faced with a usecase that requires us to delete specific redis key(s) on demand to manipulate the rate limiting behaviour.
This PR adds `del` function to `limitd` client interface.
Upon agreement, for now, the function will only support a single key deletion at a time.
https://redis.io/docs/latest/commands/del/

feat: add ability to delete redis keys on demand

---

.github/workflows/redis-tests.yml
.github/workflows/valkey-tests.yml
Makefile
README.md
docker-compose-cluster.yml
docker-compose.yml

After Redis [decided to change its license](https://redis.io/blog/redis-adopts-dual-source-available-licensing/), the community seems to be moving towards the adoption of [Valkey](https://valkey.io/).
This PR initiates the support of Valkey by running our entire test suite against both Redis and Valkey.
https://redis.io/blog/redis-adopts-dual-source-available-licensing/
https://valkey.io/
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the …

added tests with Valkey

---

.github/workflows/redis-tests.yml
.github/workflows/unit-tests.yml
.github/workflows/valkey-tests.yml
Makefile
lib/db.js
package.json
test/unit/cb.tests.js
test/unit/db.tests.js
test/unit/utils.tests.js
test/unit/validation.tests.js

We realised that overriding limits seemed to bring back the sliding window behaviour if the limit was set to fixed_window:
During testing we created an override setting the limit to 100 RPS. The moment the override hit the configuration, the behavior changed, we saw the sliding window behavior back in place.
After removing the override we were back to the fixed_window behavior.
> Include any links supporting this change such as a:
>
> - GitHub Issue/PR …

fix: carry over fixed_window attribute to overrides
